name: variables and secrets

env:
  WF_VAR: "workflow level variable"
on:
  push:
    
jobs:
  test-expression:
    name: job to test expression
    runs-on: ubuntu_latest
    env:
      aBoolean: ${{false}}
      aNull: ${{null}}
      aNumber: ${{42}}
      aString: This is a String
    steps:
      - name: test null
        if: (env.aNull == null)
        run: echo "this variable is null"
      - name: test Boolean
        if: ${{fromJSON(env.aBoolean)}}
        run: echo "this job wont run as our variable is false"
      - name: contains function
        if: ${{contains(env.aString,'this')}}
        run: |
          echo "our string contains the wod this"
          echos "but here is a typo that will make this step fail"
      - name: test status check and format function
        if: ${{failure() }}
        env:
          FORMAT_VAR: ${{format("gitHub {0} {1} {2}",'actions','is','awesome!')}}
        run: |
          echo "This step runs a special to clean up after failed step"
          echo ${{env.FORMAT_VAR}}
      - name: function and always status check
        if: ${{startWith(env.aString,'this') && always()}}
        run: sleep 60
      - name: TEST cancel status check
        if: ${{cancelled()}}
        run: echo "this job run if one workflow is cancelled" 
      
  test_vaiables:
    if: (github.even_name == "pull_request")
    env:
      JOB_VAR: "JOB LEVEL VARIABLE"
    name: job to test variables
    runs-on: ubuntu-latest
    steps:
      - name: test_variables
        id: stepVar
        env:
          STEP_VAR: "STep Level Variable"
        run: |
          echo ${{github.actor}}
          echo $GITHUB_JOB
          echo $WF_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo ${{vars.CONF_VAR}}
          echo ${{secrets.A_SECRET}}
